/*
 * config_timer.h
 *
 *  Created on: Oct 28, 2022
 *      Author: engineer
 */

#ifndef MCAL_TIMERS_CONFIG_TIMER_H_
#define MCAL_TIMERS_CONFIG_TIMER_H_

/*
 * drivers rigsters
 *
 *
 * */




/*options for timer mode
 * 1)TIMER_NORMAL_MODE
 * TIMER_PHASE_CORRECT_MODE
 * TIMER_CTC_MODE
 * TIMER_FAST_PWM_MODE

 * */
#define TIMER0_MODE       TIMER_FAST_PWM_MODE

/*options for oc0 pin
 * 1- OC0_PIN_DISCONNECTED
 *  OC0_PIN_TOGGLE
 *  OC0_PIN_CLEARED
 *   OC0_PIN_SET
 * */
#define OC0_MODE  OC0_PIN_TOGGLE


/*OPTIONS FOR clock pin
 * NO_CLK_SOURCE
 * SYSTEM_CLK
 * PRESCALAR_OVER_8
 *  PRESCALAR_OVER_64
 *   PRESCALAR_OVER_256
 *   PRESCALAR_OVER_1024
 *   PRESCALAR_OVER_FALLING_EDGE
 *   PRESCALAR_OVER_RISING_EDGE
 *
 * */
#define CLK_SOURCE_MODE       PRESCALAR_OVER_1024

/*options for tov0  NORMAL interrupt
 *NORMAL_INTERRUPT_ENABLED
 *NORMAL_INTERRUPT_DISENABLED
 *

 * */


#define  TIMER0_NORMAL_MODE_INTERRUPT    NORMAL_INTERRUPT_ENABLED


/*options for CTC interrupt
 *CTC_INTERRUPT_ENABLED
 *CTC_INTERRUPT_DISENABLED
 *

 * */


#define  TIMER0_CTC_MODE_INTERRUPT    CTC_INTERRUPT_ENABLED

/*options for fast
 * 1)FAST_PWM_OC0_DISCONNECTED
 * 2)FAST_PWM_OC0_NON_INVERTING
 FAST_PWM_OC0_INVERTING

 * */
#define TIMER_FAST_PWM_MODE_CONDITION     FAST_PWM_OC0_NON_INVERTING
/*options for fast
 * 1)PHASE_CORRECT_OC0_DISCONNECTED
 * 2)PHASE_CORRECT_OC0_NON_INVERTING
 PHASE_CORRECT_OC0_INVERTING

 * */
#define TIMER_PHASE_CORRECT_MODE    PHASE_CORRECT_OC0_NON_INVERTING

#endif /* MCAL_TIMERS_CONFIG_TIMER_H_ */
